### ISSUE TITLE
千和易的 阿里云的密钥你给公开了 请删除掉。

### ISSUE THREAD

**Issue by BlueOfTheSea** [xiaoyang2626/db_tool#1]
千和易的 阿里云的密钥你给公开了 请删除掉。

**Comment by xiaoyang2626** [comment]
你好 请问我在哪里公开了呢?

> 千和易的阿里云的密匙你给公开放了请删减。

**Comment by BlueOfTheSea** [comment]
明天我把代码截图给你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月15日 18:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaoyang2626/db_tool] 千和易的 阿里云的密钥你给公开了 请删除掉。 (Issue #1) |

你好 请问我在哪里公开了呢?

千和易的阿里云的密匙你给公开放了请删减。

**Comment by xiaoyang2626** [comment]
> 明天我把代码截图给你
> [……](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年05月15日 18:03 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [xiaoyang2626/db_tool] 千和易的 阿里云的密钥你给公开了 请删除掉。 (Issue #1) | 你好 请问我在哪里公开了呢? 千和易的阿里云的密匙你给公开放了请删减。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你的issue与这个库无关的话 那我就先关闭了  你可以发送至我的邮箱yanghaocheng_2008@163.com

**Comment by BlueOfTheSea** [comment]
嗯嗯，关闭吧



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月15日 18:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xiaoyang2626/db_tool] 千和易的 阿里云的密钥你给公开了 请删除掉。 (Issue #1) |

明天我把代码截图给你
……
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年05月15日 18:03 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [xiaoyang2626/db_tool] 千和易的 阿里云的密钥你给公开了 请删除掉。 (Issue #1) | 你好 请问我在哪里公开了呢? 千和易的阿里云的密匙你给公开放了请删减。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

你的issue与这个库无关的话 那我就先关闭了 ***@***.***
